# Generated by Django 4.2.3 on 2023-07-21 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Item',
        ),
    ]
