# Generated by Django 4.2.3 on 2023-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_orders_cart_items_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ManyToManyField(to='store.item'),
        ),
    ]
