# Generated by Django 4.2.3 on 2023-07-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_order_order_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders',
            new_name='items',
        ),
    ]
