# Generated by Django 4.2.3 on 2023-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_item_formatted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='formatted_price',
            field=models.FloatField(default=0.0),
        ),
    ]
